### PR TITLE
Wiki translation

### LINKED ISSUE #24: Traduzione wiki
Tutta la documentazione già presente sulla [wiki](https://csunibo.github.io/wiki) andrebbe tradotta in Inglese perché possa essere consultata anche da chi frequenta il corso di AI (o eventuali futuri CdL in Inglese del dipartimento) senza parlare Italiano.

### PR DESCRIPTION
**Pull request by MattiaFerrarini**
Closes #24  

La traduzione è stata fatta da ChatGPT e mi sembra vada bene.

### CODE REVIEW

**Review by foxyseta — CHANGES_REQUESTED** [review]
I personally would have NOT recommended the use of general-purpose chatbots for this task. Traditional automatic translators also use DNNs anyway, without all the problems brought about by chatbots.

Still, the translation looks good as expected. The only edits that you should manually do are the internal links to other pages of the wiki (we do not want to point to the Italian wiki from the English one!).

**Comment by MattiaFerrarini** [comment]
You are right. I have now fixed the internal links.

**Review by foxyseta — APPROVED** [review]

**Comment by foxyseta** [comment]
@ali-benny feel free to merge and deploy.

**Comment by foxyseta** [comment]
Have you deployed already?

**Comment by samuelemusiani** [comment]
> Have you deployed already?

Done it now

**Pull request merged**
